files:
  - source: /TMessagesProj/src/main/res/values/strings_nullgram.xml
    ignore:
      - /TMessagesProj/src/main/res/values-v*
    translation: /TMessagesProj/src/main/res/values-%two_letters_code%/%original_file_name%
    translate_content: 0
