include ':TMessagesProj'
include ':openpgp-api'
include ':jlatexmath'
project(':jlatexmath').projectDir = file('TMessagesProj/lib/jlatexmath/jlatexmath')

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

gradle.ext.androidxMediaModulePrefix = 'TMessagesProj_Modules:media3:media-'
apply from: file("TMessagesProj_Modules/media/core_settings.gradle")